### ISSUE TITLE
Serialised Arena object does not load from file

### ISSUE THREAD

**Issue by pgmann** [pgmann/SpectatorPlus#15]
The following error occurs when an arena exists and the plugin attempts to load it on enable, or any other time it uses `reloadConfig();`. @AmauryCarrade, would you help please, since you were the one wrote the ArenasManager in the first place?

Error log:

``` java
09.09 12:30:05 [Multicraft] Skipped 44 lines due to rate limit (30/s)
09.09 12:30:03 [Server] INFO at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [custom.jar:git-Spigot-1624]
09.09 12:30:03 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [custom.jar:git-Spigot-1624]
09.09 12:30:03 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [custom.jar:git-Spigot-1624]
09.09 12:30:03 [Server] INFO at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [custom.jar:git-Spigot-1624]
09.09 12:30:03 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [custom.jar:git-Spigot-1624]
09.09 12:30:03 [Server] INFO at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [custom.jar:git-Spigot-1624]
09.09 12:30:03 [Server] INFO at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:184) [custom.jar:git-Spigot-1624]
09.09 12:30:03 [Server] INFO at net.minecraft.server.v1_7_R4.PacketPlayInChat.handle(PacketPlayInChat.java:65) [custom.jar:git-Spigot-1624]
09.09 12:30:03 [Server] INFO at net.minecraft.server.v1_7_R4.PacketPlayInChat.a(PacketPlayInChat.java:28) [custom.jar:git-Spigot-1624]
09.09 12:30:03 [Server] INFO at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:850) [custom.jar:git-Spigot-1624]
09.09 12:30:03 [Server] INFO at net.minecraft.server.v1_7_R4.PlayerConnection.handleCommand(PlayerConnection.java:1013) [custom.jar:git-Spigot-1624]
09.09 12:30:03 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:767) [custom.jar:git-Spigot-1624]
09.09 12:30:03 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) [custom.jar:git-Spigot-1624]
09.09 12:30:03 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [custom.jar:git-Spigot-1624]
09.09 12:30:03 [Server] INFO at co.technius.PluginManager.PMCommandExecutor.onCommand(PMCommandExecutor.java:497) [PluginManager.jar:?]
09.09 12:30:03 [Server] INFO at co.technius.PluginManager.PMCommandExecutor.loadCmd(PMCommandExecutor.java:450) [PluginManager.jar:?]
09.09 12:30:03 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [custom.jar:git-Spigot-1624]
09.09 12:30:03 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [custom.jar:git-Spigot-1624]
09.09 12:30:03 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) [custom.jar:git-Spigot-1624]
09.09 12:30:03 [Server] INFO at com.pgcraft.spectatorplus.SpectatorPlus.onEnable(SpectatorPlus.java:84) [SpectatorPlus-B2.0.jar:?]
09.09 12:30:03 [Server] INFO at com.pgcraft.spectatorplus.SpectatorPlus.reloadConfig(SpectatorPlus.java:575) [SpectatorPlus-B2.0.jar:?]
09.09 12:30:03 [Server] INFO at com.pgcraft.spectatorplus.ConfigAccessor.reloadConfig(ConfigAccessor.java:58) [SpectatorPlus-B2.0.jar:?]
09.09 12:30:03 [Server] INFO at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:180) [custom.jar:git-Spigot-1624]
09.09 12:30:03 [Server] INFO at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:169) ~[custom.jar:git-Spigot-1624]
09.09 12:30:03 [Server] INFO at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:226) ~[custom.jar:git-Spigot-1624]
09.09 12:30:03 [Server] INFO at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57) ~[custom.jar:git-Spigot-1624]
09.09 12:30:03 [Server] INFO org.bukkit.configuration.InvalidConfigurationException: org.yaml.snakeyaml.error.YAMLException: Could not deserialize object
09.09 12:30:03 [Server] INFO [12:30:03 ERROR]: Cannot load plugins/SpectatorPlus/setup.yml
09.09 12:30:03 [Server] INFO [12:30:03 INFO]: [SpectatorPlus] Enabling SpectatorPlus v2.0
```

`setup.yml`:

``` yml
active: true
xPos: -606.5
yPos: 72.0
zPos: -129.5
nextarena: 1
mode: arena
world: Games
arenas:
  6f40672e-2e88-4b28-945f-8645daf40e50:
    ==: com.pgcraft.spectatorplus.Arena
    id: 6f40672e-2e88-4b28-945f-8645daf40e50
    registered: true
    corner1:
      ==: Vector
      x: -597.0
      y: 85.0
      z: 0.0
    corner2:
      ==: Vector
      x: -673.0
      y: 64.0
      z: -77.0
    name: Event
    lobby.world: Games
    lobby.location:
      ==: Vector
      x: -633.5
      y: 102.0
      z: -33.5
    world: Games

```
