### ISSUE TITLE
Command blocking whitelist/blacklist

### ISSUE THREAD

**Issue by pgmann** [pgmann/SpectatorPlus#29]
_--- Imported from dev.bukkit.org: original issue reported by TheOnlyRealTGS ---_
Add a whitelist where you can define which commands are allowed.

```yml
block-cmds:
  enabled: true
  whitelist:
    - msg
    - r
    - w
    - list
```
