### ISSUE TITLE
Allow the spectators to pass through a wall

### ISSUE THREAD

**Issue by AmauryCarrade** [pgmann/SpectatorPlus#35]
As example by double-clicking on a wall (without a specific item for that).

The question is: how the spectators will be informed about the option?

Also, the config (`toggles.yml` — everyday, more non-toggle options):

``` yaml
# Allows the spectators to pass through the walls by double-clicking on it.
spectatorsPassThroughWalls: true
# The search distance for a spot where the spectator can be teleported, in blocks
spectatorsThroughWallsMaxSearchDistance: 15 # if you have a shorter config key... :D
```
